### ISSUE TITLE
Dúvida em relação às variáveis para utilizar no elemento PadesVisualText.

### ISSUE THREAD

**Issue by adolfobrunno** [LacunaSoftware/PkiExpressJava#2]
Olá, estou com uma dúvida em relação às variáveis para utilizar no elemento PadesVisualText.

No exemplo, vocês disponibilizam as variáveis {{name}} e {{br_cpf_formatted}}. Porém, no meu caso de uso, o certificado pertence a um CNPJ. Quando uso o {{name}} me retorna o nome da pessoa física responsável pela empresa, e não o nome da empresa.  Como consigo ver quais as variáveis disponíveis para utilização? 

Desde já agradeço quaisquer informações.

**Comment by MimyS** [comment]
Olá, @adolfobrunno !

O nome da empresa pode ser obtido pela tag `{{br_company}}` e o cnpj pela `{{br_cnpj_formatted}}`.

No momento, a lista de tags suportadas pode ser visualizada no arquivo [PAdES Tag](https://github.com/LacunaSoftware/RestPkiSamples/blob/master/PadesTags.md) do repositório RestPkiSamples.

**Comment by adolfobrunno** [comment]
Olá, @MimyS . Muito obrigado pela resposta!
